"""Initial migration

Revision ID: 99a9c5d56391
Revises: 
Create Date: 2025-09-08 23:16:39.668360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a9c5d56391'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('cpf', 'cnpj', name='documenttype'), nullable=False),
    sa.Column('rg_ie', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('secondary_email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_access', sa.Boolean(), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_document'), 'clients', ['document'], unique=True)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'architect', 'assistant', name='userrole'), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table('stage_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('default_duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('estimated_end_date', sa.Date(), nullable=False),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', 'cancelled', name='projectstatus'), nullable=False),
    sa.Column('work_address', sa.JSON(), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('project_clients',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'client_id')
    )

    op.create_table('stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', 'on_hold', name='stagestatus'), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=False),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=False),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'partial', 'paid', name='paymentstatus'), nullable=False),
    sa.Column('specific_data', sa.JSON(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage_type_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stage_type_id'], ['stage_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('stored_name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('document', 'image', 'plan', 'render', 'contract', name='filecategory'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )

    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'completed', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='taskpriority'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Inserir dados padrão para tipos de etapa
    from sqlalchemy import text
    import json

    # Dados padrão dos tipos de etapa baseados no fluxo da Crialt Arquitetura
    stage_types_data = [
        {
            'name': 'Levantamento',
            'description': 'Levantamento do local e medições',
            'scope': {
                'local_visita': {'type': 'string', 'required': True, 'label': 'Local da Visita'},
                'data_visita': {'type': 'date', 'required': True, 'label': 'Data da Visita'},
                'responsavel': {'type': 'string', 'required': True, 'label': 'Responsável'},
                'observacoes_local': {'type': 'text', 'required': False, 'label': 'Observações do Local'}
            },
            'default_duration_days': 3
        },
        {
            'name': 'Briefing',
            'description': 'Reunião para definição do briefing com o cliente',
            'scope': {
                'preferencias_cliente': {'type': 'text', 'required': True, 'label': 'Preferências do Cliente'},
                'orcamento_cliente': {'type': 'number', 'required': False, 'label': 'Orçamento do Cliente'},
                'prazo_desejado': {'type': 'date', 'required': False, 'label': 'Prazo Desejado'},
                'estilo_preferido': {'type': 'string', 'required': False, 'label': 'Estilo Preferido'}
            },
            'default_duration_days': 2
        },
        {
            'name': 'Estudo Preliminar',
            'description': 'Desenvolvimento do estudo preliminar',
            'scope': {
                'numero_alternativas': {'type': 'number', 'required': True, 'label': 'Número de Alternativas'},
                'tipo_apresentacao': {'type': 'string', 'required': True, 'label': 'Tipo de Apresentação'},
                'revisoes_incluidas': {'type': 'number', 'required': True, 'label': 'Revisões Incluídas'},
                'entrega_3d': {'type': 'boolean', 'required': False, 'label': 'Entrega de Imagens 3D'}
            },
            'default_duration_days': 14
        },
        {
            'name': 'Projeto Executivo',
            'description': 'Desenvolvimento do projeto executivo detalhado',
            'scope': {
                'plantas_incluidas': {'type': 'array', 'required': True, 'label': 'Plantas Incluídas'},
                'especialidades': {'type': 'array', 'required': True, 'label': 'Especialidades (Elétrica, Hidráulica, etc.)'},
                'detalhamentos': {'type': 'array', 'required': False, 'label': 'Detalhamentos Específicos'},
                'memorial_descritivo': {'type': 'boolean', 'required': True, 'label': 'Memorial Descritivo'}
            },
            'default_duration_days': 30
        },
        {
            'name': 'Assessoria Pós-Projeto',
            'description': 'Acompanhamento e assessoria durante a execução',
            'scope': {
                'cronograma_visitas': {'type': 'array', 'required': True, 'label': 'Cronograma de Visitas'},
                'tipo_acompanhamento': {'type': 'string', 'required': True, 'label': 'Tipo de Acompanhamento'},
                'responsabilidades': {'type': 'text', 'required': True, 'label': 'Responsabilidades'},
                'prazo_assessoria': {'type': 'number', 'required': True, 'label': 'Prazo da Assessoria (meses)'}
            },
            'default_duration_days': 90
        }
    ]

    # Inserir os tipos de etapa padrão
    connection = op.get_bind()
    import time
    from datetime import datetime

    base_timestamp = time.time()

    for i, stage_type in enumerate(stage_types_data):
        scope_json = json.dumps(stage_type['scope'])
        # Adiciona 1 segundo para cada stage_type para garantir ordem diferente
        stage_created_at = datetime.fromtimestamp(base_timestamp + i)

        connection.execute(
            text("""
                INSERT INTO stage_types (id, name, description, scope, default_duration_days, is_active, created_at, updated_at)
                VALUES (
                    gen_random_uuid(),
                    :name,
                    :description,
                    :scope,
                    :default_duration_days,
                    true,
                    :created_at,
                    :updated_at
                )
            """),
            {
                'name': stage_type['name'],
                'description': stage_type['description'],
                'scope': scope_json,
                'default_duration_days': stage_type['default_duration_days'],
                'created_at': stage_created_at,
                'updated_at': stage_created_at
            }
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('files')
    op.drop_table('stages')
    op.drop_table('project_clients')
    op.drop_table('projects')
    op.drop_table('stage_types')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_document'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
